// Category emoji map
export const CATEGORY_EMOJIS: Record<string, string> = {
  'Math': '🧮',
  'Dynamic Programming': '💡',
  'Recursion': '🔄',
  'Memoization': '🧠',
  'Database': '🗄️',
  'String': '📝',
  'Tree': '🌳',
  'Depth-First Search': '🔍',
  'Breadth-First Search': '🌊',
  'Binary Search Tree': '🔐',
  'Binary Tree': '🌲',
  'Two Pointers': '👆',
  'Array': '📊',
  'Greedy': '🏆',
  'Sorting': '🔢',
  'Counting Sort': '🔢',
  'Matrix': '⬛',
  'Simulation': '🎮',
  'String Matching': '🔎',
  'Hash Function': '#️⃣',
  'Hash Table': '🗃️',
  'Stack': '📚',
  'Sliding Window': '🪟',
  'Bit Manipulation': '⚡',
  'Design': '🏗️',
  'Heap (Priority Queue)': '🏔️',
  'Data Stream': '🌊',
  'Linked List': '🔗',
  'Prefix Sum': '➕',
  'Geometry': '📐',
  'Graph Theory': '🕸️',
  'Shortest Path': '🗺️',
  'Ordered Set': '📋',
  'Enumeration': '🔢',
  'Number Theory': '🔢',
  'Union-Find': '🤝',
  'Queue': '📨',
  'Topological Sort': '📊',
  'Game Theory': '🎯',
  'Combinatorics': '🎲',
  'Bitmask': '🔲',
  'Monotonic Stack': '📈',
  'Backtracking': '↩️',
};

// Category group color accents (warm=math/dp, cool=trees/graphs, etc.)
export const CATEGORY_COLORS: Record<string, string> = {
  'Math': 'bg-orange-100 text-orange-700 border-orange-200',
  'Dynamic Programming': 'bg-amber-100 text-amber-700 border-amber-200',
  'Recursion': 'bg-yellow-100 text-yellow-700 border-yellow-200',
  'Memoization': 'bg-yellow-100 text-yellow-700 border-yellow-200',
  'Database': 'bg-slate-100 text-slate-700 border-slate-200',
  'String': 'bg-pink-100 text-pink-700 border-pink-200',
  'String Matching': 'bg-pink-100 text-pink-700 border-pink-200',
  'Tree': 'bg-emerald-100 text-emerald-700 border-emerald-200',
  'Binary Tree': 'bg-emerald-100 text-emerald-700 border-emerald-200',
  'Binary Search Tree': 'bg-teal-100 text-teal-700 border-teal-200',
  'Depth-First Search': 'bg-cyan-100 text-cyan-700 border-cyan-200',
  'Breadth-First Search': 'bg-sky-100 text-sky-700 border-sky-200',
  'Graph Theory': 'bg-blue-100 text-blue-700 border-blue-200',
  'Shortest Path': 'bg-blue-100 text-blue-700 border-blue-200',
  'Two Pointers': 'bg-violet-100 text-violet-700 border-violet-200',
  'Array': 'bg-indigo-100 text-indigo-700 border-indigo-200',
  'Greedy': 'bg-lime-100 text-lime-700 border-lime-200',
  'Sorting': 'bg-green-100 text-green-700 border-green-200',
  'Counting Sort': 'bg-green-100 text-green-700 border-green-200',
  'Matrix': 'bg-purple-100 text-purple-700 border-purple-200',
  'Hash Table': 'bg-rose-100 text-rose-700 border-rose-200',
  'Hash Function': 'bg-rose-100 text-rose-700 border-rose-200',
  'Stack': 'bg-fuchsia-100 text-fuchsia-700 border-fuchsia-200',
  'Backtracking': 'bg-orange-100 text-orange-700 border-orange-200',
  'Bit Manipulation': 'bg-yellow-100 text-yellow-700 border-yellow-200',
  'Sliding Window': 'bg-cyan-100 text-cyan-700 border-cyan-200',
  'Linked List': 'bg-indigo-100 text-indigo-700 border-indigo-200',
  'Design': 'bg-slate-100 text-slate-700 border-slate-200',
  'Heap (Priority Queue)': 'bg-orange-100 text-orange-700 border-orange-200',
  'Prefix Sum': 'bg-teal-100 text-teal-700 border-teal-200',
  'Union-Find': 'bg-blue-100 text-blue-700 border-blue-200',
  'Topological Sort': 'bg-violet-100 text-violet-700 border-violet-200',
  'Game Theory': 'bg-red-100 text-red-700 border-red-200',
  'Combinatorics': 'bg-amber-100 text-amber-700 border-amber-200',
  'Bitmask': 'bg-yellow-100 text-yellow-700 border-yellow-200',
  'Monotonic Stack': 'bg-fuchsia-100 text-fuchsia-700 border-fuchsia-200',
  'Geometry': 'bg-pink-100 text-pink-700 border-pink-200',
  'Number Theory': 'bg-orange-100 text-orange-700 border-orange-200',
  'Enumeration': 'bg-lime-100 text-lime-700 border-lime-200',
  'Ordered Set': 'bg-green-100 text-green-700 border-green-200',
  'Queue': 'bg-sky-100 text-sky-700 border-sky-200',
  'Data Stream': 'bg-cyan-100 text-cyan-700 border-cyan-200',
  'Simulation': 'bg-purple-100 text-purple-700 border-purple-200',
};

export function getCategoryColor(cat: string): string {
  return CATEGORY_COLORS[cat] || 'bg-gray-100 text-gray-700 border-gray-200';
}

export const LANGUAGE_COLORS: Record<string, { bg: string; text: string }> = {
  Python: { bg: '#3572A5', text: '#fff' },
  Java: { bg: '#B07219', text: '#fff' },
  TypeScript: { bg: '#3178C6', text: '#fff' },
  JavaScript: { bg: '#F7DF1E', text: '#000' },
  Elixir: { bg: '#6E4A7E', text: '#fff' },
  Erlang: { bg: '#B83998', text: '#fff' },
  SQL: { bg: '#E34C26', text: '#fff' },
  Racket: { bg: '#3E5BA9', text: '#fff' },
  'C++': { bg: '#00599C', text: '#fff' },
};

export function getLangColor(lang: string) {
  return LANGUAGE_COLORS[lang] || { bg: '#6B7280', text: '#fff' };
}

export const DIFFICULTY_STYLES = {
  Easy: {
    badge: 'bg-green-100 text-green-700 border-green-300',
    border: 'border-l-green-400',
    dot: 'bg-green-400',
    text: 'text-green-600',
  },
  Medium: {
    badge: 'bg-amber-100 text-amber-700 border-amber-300',
    border: 'border-l-amber-400',
    dot: 'bg-amber-400',
    text: 'text-amber-600',
  },
  Hard: {
    badge: 'bg-red-100 text-red-700 border-red-300',
    border: 'border-l-red-400',
    dot: 'bg-red-400',
    text: 'text-red-600',
  },
};
