
(define/contract (find-safe-walk grid health)
  (-> (listof (listof exact-integer?)) exact-integer? boolean?)
  (define m (length grid))
  (define n (length (first grid)))
  (define dist (make-vector m))
  (for ([i (in-range m)])
    (vector-set! dist i (make-vector n +inf.0)))
  (define dq '())
  (define (push-front x) (set! dq (cons x dq)))
  (define (push-back x) (set! dq (append dq (list x))))
  (define (pop-front)
    (let ([x (car dq)])
      (set! dq (cdr dq))
      x))
  (define start-cost (list-ref (first grid) 0))
  (vector-set! (vector-ref dist 0) 0 start-cost)
  (push-front (cons 0 0))
  (define dirs '((1 . 0) (-1 . 0) (0 . 1) (0 . -1)))
  (let loop ()
    (unless (null? dq)
      (define p (pop-front))
      (define x (car p))
      (define y (cdr p))
      (define d (vector-ref (vector-ref dist x) y))
      (for ([dir dirs])
        (define nx (+ x (car dir)))
        (define ny (+ y (cdr dir)))
        (when (and (<= 0 nx) (< nx m) (<= 0 ny) (< ny n))
          (define w (list-ref (list-ref grid nx) ny))
          (define nd (+ d w))
          (when (< nd (vector-ref (vector-ref dist nx) ny))
            (vector-set! (vector-ref dist nx) ny nd)
            (if (= w 0)
                (push-front (cons nx ny))
                (push-back (cons nx ny))))))
      (loop)))
  (< (vector-ref (vector-ref dist (- m 1)) (- n 1)) health))