(define/contract (int-to-roman num)
  (-> exact-integer? string?)
  (define vals #(1000 900 500 400 100 90 50 40 10 9 5 4 1))
  (define syms #("M" "CM" "D" "CD" "C" "XC" "L" "XL" "X" "IX" "V" "IV" "I"))
  (define out "")
  (define n num)
  (for ([i (in-range (vector-length vals))])
    (let loop ()
      (when (>= n (vector-ref vals i))
        (set! out (string-append out (vector-ref syms i)))
        (set! n (- n (vector-ref vals i)))
        (loop))))
  out)