(define/contract (max-area height)
  (-> (listof exact-integer?) exact-integer?)
  (define v (list->vector height))
  (define l 0)
  (define r (- (vector-length v) 1))
  (define ans 0)
  (let loop ()
    (when (< l r)
      (define hl (vector-ref v l))
      (define hr (vector-ref v r))
      (define area (* (min hl hr) (- r l)))
      (when (> area ans)
        (set! ans area))
      (if (< hl hr)
          (set! l (add1 l))
          (set! r (sub1 r)))
      (loop)))
  ans)